#ifndef KERBEROS_SRC_MA_COMM_ERROR_CODES_H_
#define KERBEROS_SRC_MA_COMM_ERROR_CODES_H_

#define MA_COMM_FALSE					0
#define MA_COMM_TRUE					1

#define MA_COMM_SUCCESS					0
#define MA_COMM_INVALID_PARAMETER		1
#define MA_COMM_OUT_OF_MEMORY			2
#define MA_COMM_INVALID_STATE			3


#endif /* KERBEROS_SRC_MA_COMM_ERROR_CODES_H_ */
